name: Daily NVDA Report

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 13 * * *'  # daily
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.2.2
      with:
        ref: main
        persist-credentials: true   # ensures GITHUB_TOKEN can push
        fetch-depth: 0             # full history for commits

    - name: Set up Python
      run: python3 --version

    - name: Install dependencies
      run: pip install yfinance feedparser

    - name: Generate HTML
      run: python report.py

    - name: Commit updated report
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add index.html report/index.html
        git commit -m "Daily NVDA update" || echo "No changes"
        git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} HEAD:main
